const images = {
    phone:require('../../source/phone.png'),
    gift:require('../../source/gift.gif'),
    weather: require('../../source/weather.png'),
    callPerson: require('../../source/call.png'),
    guide_next: require('../../source/guide_next.png'),
    guide1: require('../../source/guide1.png'),
    guide2: require('../../source/guide2.png'),
    guide3: require('../../source/guide3.png'),
    one1: require('../../source/one1.png'),
    bottomarea: require('../../source/bottomarea.png'),
    two: require('../../source/two.png'),
    three: require('../../source/three.png'),
    out_exit: require('../../source/out_exit.png'),
    cny: require('../../source/cny.png'),
    hkd: require('../../source/hkd.png'),
    mop: require('../../source/mop.png'),
    default_img: require('../../source/default_img.png'),
    month: require('../../source/month.png'),
    monthE: require('../../source/monthE.png'),
    home_competition: require('../../source/home/home_competition.png'),
    home_def_harid: require('../../source/home/home_def_harid.png'),
    home_follow: require('../../source/home/home_follow.png'),
    home_gold: require('../../source/home/home_gold.png'),
    home_more: require('../../source/home/home_side.png'),
    home_over_one: require('../../source/home/home_over_one.png'),
    home_over: require('../../source/home/home_over.png'),
    home_poker: require('../../source/home/home_poker.png'),
    home_prize: require('../../source/home/home_prize.png'),
    home_bg: require('../../source/home/home_bg_image.png'),
    home_bg_races: require('../../source/home/home_bg_race.png'),
    home_no: require('../../source/home/home_no.png'),
    home_fail: require('../../source/home/home_fail.png'),
    home_avatar: require('../../source/home/home_avatar.png'),
    sign_bg: require('../../source/login/sign_bg_image.png'),
    sign_choice_no: require('../../source/login/sign_choice_no.png'),
    sign_choice: require('../../source/login/sign_choice.png'),
    sign_close: require('../../source/login/sign_close.png'),
    sign_eye_open: require('../../source/login/sign_eye_open.png'),
    sign_eye: require('../../source/login/sign_eye.png'),
    sign_number: require('../../source/login/sign_number.png'),
    sign_password: require('../../source/login/sign_password.png'),
    sign_return: require('../../source/login/sign_retrun.png'),
    slide_edit: require('../../source/slide/sidebar_modify.png'),
    slide_order: require('../../source/slide/sidebar_order.png'),
    slide_service: require('../../source/slide/sidebar_service.png'),
    slide_setting: require('../../source/slide/sidebar_set-up.png'),
    ticket_arrow: require('../../source/buy/ticket_arrow.png'),
    ticket_prompt: require('../../source/buy/ticket_prompt.png'),
    ticket_security: require('../../source/buy/ticket_security.png'),
    prompt_service: require('../../source/buy/prompt_service.png'),
    e_ticket_buy_zh: require('../../source/buy/e_ticket_buy_zh.png'),
    e_ticket_buy_en: require('../../source/buy/e_ticket_buy_en.png'),
    name_id: require('../../source/buy/name_id.png'),
    set_closed: require('../../source/setting/set_closed.png'),
    set_exclamation: require('../../source/setting/set_exclamation.png'),
    set_eye_close: require('../../source/setting/set_eye_close.png'),
    set_eye: require('../../source/setting/set_eye.png'),
    set_fork: require('../../source/setting/set_fork.png'),
    set_fork2: require('../../source/setting/set_fork2.png'),
    set_more: require('../../source/setting/set_more.png'),
    set_open: require('../../source/setting/set_open.png'),
    load_no_data: require('../../source/load/load_no_data.png'),
    load_refresh: require('../../source/load/load_refresh.png'),
    load_wifi: require('../../source/load/load_wifi.png'),
    races_bg: require('../../source/races/races_bg.png'),
    user_real_failed: require('../../source/order/user_real_failed.png'),
    user_real_pending: require('../../source/order/user_real_pending.png'),
    schedule: require('../../source/races/schedule.png'),
    search: require('../../source/races/search.png'),
    prev: require('../../source/races/prev.png'),
    search_gray: require('../../source/races/search_gray.png'),
    back: require('../../source/races/back.png'),
    slid_business: require('../../source/slide/slid_business.png'),
    set_poker: require('../../source/setting/set_poker.png'),
    race_time: require('../../source/races/race_time.png'),
    empty_image: require('../../source/empty/empty_ticket.png'),
    news_share: require('../../source/news/news_share.png'),
    race_type: require('../../source/races/race_type.png'),
    race_type_selected: require('../../source/races/race_type_selected.png'),
    race_type_unselect: require('../../source/races/race_type_unselect.png'),
    load_error: require('../../source/load/load_error.png'),
    set_back: require('../../source/setting/set_back.png'),
    home_badge: require('../../source/home/home_badge.png'),
    up_triangle: require('../../source/order/up_triangle.png'),
    down_triangle: require('../../source/order/down_triangle.png'),
    ic_back: require('../../source/order/ic_back.png'),
    side_select: require('../../source/order/side_select.png'),
    side_selected: require('../../source/order/side_seleced.png'),
    empty_ticket: require('../../source/empty/empty_ticket.png'),
    home_img: require('../../source/home/home_img.png'),
    home_fire: require('../../source/home/home_fire.png'),
    more: require('../../source/home/more.png'),
    home_news: require('../../source/home/home_news.png'),
    home_sort1: require('../../source/home/home_sort1.png'),
    home_video1: require('../../source/home/home_video1.png'),
    item_sale: require('../../source/home/item_sale.png'),
    home_clock: require('../../source/home/home_clock.png'),
    home_adr: require('../../source/home/home_adr.png'),
    race_doing: require('../../source/home/race_doing.png'),
    race_end: require('../../source/home/race_end.png'),
    race_unstart: require('../../source/home/race_unstart.png'),
    race_wait: require('../../source/home/race_wait.png'),
    home_head: require('../../source/home/home_head.png'),
    edit: require('../../source/buy/edit.png'),
    handle: require('../../source/buy/handle.png'),
    handle2: require('../../source/buy/handle2.png'),
    adr_right: require('../../source/buy/adr_right.png'),
    adr_selected: require('../../source/buy/adr_selected.png'),
    video_play: require('../../source/news/video_play.png'),
    gold: require('../../source/rank/gold.png'),
    silver: require('../../source/rank/silver.png'),
    copper: require('../../source/rank/copper.png'),
    web_left: require('../../source/news/web_left.png'),
    web_page: require('../../source/news/web_page.png'),
    web_right: require('../../source/news/web_right.png'),
    web_refresh: require('../../source/news/web_refresh.png'),
    rank_bg: require('../../source/rank/rank_bg.png'),
    share: require('../../source/rank/share.png'),
    share2: require('../../source/rank/share2.png'),
    select_e_ticket: require('../../source/buy/select_e_ticket.png'),
    selected_e_ticket: require('../../source/buy/selected_e_ticket.png'),
    select_entity: require('../../source/buy/select_entity.png'),
    selected_entity: require('../../source/buy/selected_entity.png'),
    pay_select: require('../../source/pay/pay_select.png'),
    pay_selected: require('../../source/pay/pay_selected.png'),
    pay_close: require('../../source/pay/pay_close.png'),
    pay_card: require('../../source/pay/aliPay.png'),
    pay_ticket: require('../../source/pay/pay_ticket.png'),
    verified_add: require('../../source/verified/add.png'),
    verified_avatar: require('../../source/verified/avatar.png'),
    verified_card: require('../../source/verified/card.png'),
    verified_edit: require('../../source/verified/edit.png'),
    verified_select: require('../../source/verified/select.png'),
    verified_selected: require('../../source/verified/selected.png'),
    verified_exmple: require('../../source/verified/exmple.png'),
    verifed_passport: require('../../source/verified/passport.png'),

    my_save: require('../../source/navigation/my_save.png'),
    right2: require('../../source/navigation/right2.png'),
    task_close: require('../../source/navigation/task_close.png'),
    new_user_task: require('../../source/navigation/new_user_task.png'),
    lucky_bag: require('../../source/navigation/lucky_bag.png'),
    pukes: require('../../source/navigation/pukes.png'),
    raceBegin: require('../../source/navigation/raceBegin.png'),
    is: require('../../source/navigation/is>.png'),
    location: require('../../source/navigation/location.png'),
    time: require('../../source/navigation/time.png'),
    button: require('../../source/navigation/button.png'),
    oval: require('../../source/navigation/oval.png'),
    home: require('../../source/navigation/gray_home.png'),
    home2: require('../../source/navigation/red_home.png'),
    information: require('../../source/navigation/gray_explore.png'),
    information2: require('../../source/navigation/red_explore.png'),
    mine: require('../../source/navigation/gray_feed.png'),
    mine2: require('../../source/navigation/red_feed.png'),
    begin: require('../../source/navigation/begin.png'),
    business: require('../../source/navigation/business.png'),
    order: require('../../source/navigation/order.png'),
    settings: require('../../source/navigation/settings.png'),
    customer_service_tel: require('../../source/navigation/customer_service_tel.png'),
    speaker: require('../../source/navigation/speaker.png'),
    news_search: require('../../source/news/news_search.png'),
    video_share: require('../../source/news/video_share.png'),
    search_notice: require('../../source/navigation/search_notice.png'),
    search_notice2: require('../../source/navigation/search_notice2.png'),
    top: require('../../source/navigation/top.png'),
    coming: require('../../source/navigation/coming.png'),
    nav_mall: require('../../source/navigation/gray_msg1.png'),
    nav_malled: require('../../source/navigation/red_msg.png'),
    rightImg: require('../../source/navigation/rightImg.png'),
    shopping_cart: require('../../source/mall/cart.png'),
    mall_filter: require('../../source/mall/mall_filter.png'),
    sort_down: require('../../source/mall/sort_down.png'),
    sort_up: require('../../source/mall/sort_up.png'),
    sort: require('../../source/mall/sort.png'),
    mall_del: require('../../source/mall/mall_del.png'),
    shoppingCart: require('../../source/mall/shoppingCart.png'),
    close: require('../../source/mall/close.png'),
    closeWhite: require('../../source/mall/closeWhite.png'),
    cut: require('../../source/mall/cut.png'),
    add: require('../../source/mall/add.png'),
    mall_return: require('../../source/mall/mall_return.png'),
    mall_share: require('../../source/mall/mall_share.png'),
    search_empty: require('../../source/mall/search_empty.png'),
    camera: require('../../source/mall/camera.png'),
    mall_order_icon: require('../../source/mall/mall_order_icon.png'),

    radioSelected: require('../../source/cart/radioSelected.png'),
    radio: require('../../source/cart/radio.png'),
    emptyCart: require('../../source/cart/emptyCart.png'),
    poker_key: require('../../source/navigation/poker_key.png'),
    expand: require('../../source/order/expand.png'),
    positioning: require('../../source/order/positioning.png'),
    return_radio: require('../../source/mall/return_radio.png'),
    return_radio_selected: require('../../source/mall/return_radio_selected.png'),
    logistics: require('../../source/mall/logistics.png'),
    order_line: require('../../source/order/order_line.png'),
    mall_order: require('../../source/mall/mall_order.png'),
    ticket_order: require('../../source/mall/ticket_order.png'),
    delivery: require('../../source/mall/delivery.png'),
    mall_up: require('../../source/mall/mall_up.png'),
    loading: require('../../source/setting/loading.gif'),
    imgDel: require('../../source/mall/imgDel.png'),

    comment: require('../../source/comment/comment.png'),
    pen: require('../../source/comment/pen.png'),
    commentWhite: require('../../source/comment/commentWhite.png'),
    like: require('../../source/comment/like.png'),
    likeRed: require('../../source/comment/likeRed.png'),
    forward: require('../../source/comment/forward.png'),
    listLike: require('../../source/comment/listLike.png'),
    black_fire: require('../../source/crowd/black_fire.png'),
    poker_b: require('../../source/navigation/poker_b.png'),
    mall_order: require('../../source/navigation/mall_order.png'),
    crowd: require('../../source/navigation/crowd.png'),
    crowd_banner: require('../../source/crowd/crowd_banner.png'),
    clickImg: require('../../source/crowd/clickImg.png'),
    clickImgBlue: require('../../source/crowd/clickImgBlue.png'),
    crowd_close: require('../../source/crowd/crowd_close.png'),
    crowd_starting: require('../../source/crowd/crowd_starting.png'),
    timely_matchRed: require('../../source/crowd/timely_matchRed.png'),
    pay_help: require('../../source/mall/pay_help.png'),
    wx_pay: require('../../source/buy/weixin.png'),
    ranking: require('../../source/navigation/ranking.png'),

    APPbanner: require('../../source/crowd/APPbanner.png'),
    none: require('../../source/crowd/none.png'),

    icon_share_qq: require('../../source/share/icon_share_qq.png'),
    icon_share_sina: require('../../source/share/icon_share_sina.png'),
    icon_share_wechat: require('../../source/share/icon_share_wechat.png'),
    icon_share_wxcircle: require('../../source/share/icon_share_wxcircle.png'),
    favorites: require('../../source/share/favorites.png'),
    cancel_shoucang: require('../../source/share/cancel_shoucang.png'),
    social: {
        close: require('../../source/social/close.png'),
        article: require('../../source/social/article.png'),
        moment: require('../../source/social/moment.png'),
        close_blue: require('../../source/social/close_blue.png'),
        address: require('../../source/social/address.png'),
        icon_articleedit: require('../../source/social/icon_articleedit.png'),
        icon_send_mood: require('../../source/social/icon_send_mood.jpg'),
        reply: require('../../source/social/reply.png'),
        more_3: require('../../source/social/more_3.png'),
        like_red: require('../../source/social/like_red.png'),
        like_gray: require('../../source/social/like_gray.png'),
        comment_gray: require('../../source/social/comment_gray.png'),
        icon_address_s: require('../../source/social/icon_address_s.png'),
        article_delete: require('../../source/social/delete.png'),
        more_4: require('../../source/social/more_4.png'),
        user_topic: require('../../source/social/user_topic.png'),
        mine_moment: require('../../source/social/mine_moment.png'),
        mall: require('../../source/social/mall.png'),
        right: require('../../source/social/>.png'),
        crowd: require('../../source/social/crowd.png'),
        back: require('../../source/social/back.png'),
        male: require('../../source/social/male.png'),
        woman: require('../../source/social/womale.png'),
        self_msg: require('../../source/social/icon_selfmsg.png'),
        other_msg: require('../../source/social/icon_othermsg.png'),
        chat_more: require('../../source/social/icon_chat_more.png'),
        chat_emoji: require('../../source/social/icon_chat_emoji.png'),
        chat_picture: require('../../source/social/icon_chat_picture.png'),
        chat_takephoto: require('../../source/social/icon_chat_takephoto.png'),
        close_camera: require('../../source/social/icon_closeCamera.png'),
        cut_camera: require('../../source/social/icon_cutCamera.png'),
        take_photo: require('../../source/social/icon_take_photo.png'),
        play_video: require('../../source/social/icon_video_play.png'),
        chat_left: require('../../source/social/icon_chat_left.png'),
        chat_right: require('../../source/social/icon_chat_right.png'),
        voice_left: require('../../source/social/icon_voice_left.png'),
        voice_right: require('../../source/social/icon_voice_right.png'),
        keyboard: require('../../source/social/icon_chat_keyboard.png'),
        voiceinput: require('../../source/social/icon_chat_voiceinput.png'),
        send_failure: require('../../source/social/send_failure.png'),
    },
    macau: {
        search: require('../../source/macau/search.png'),
        book: require('../../source/macau/book.png'),
        entertainment: require('../../source/macau/entertainment.png'),
        food: require('../../source/macau/food.png'),
        gift: require('../../source/macau/gift.png'),
        hotel: require('../../source/macau/hotel.png'),
        rate_exchange: require('../../source/macau/rate_exchange.png'),
        store: require('../../source/macau/store.png'),
        viewpoint: require('../../source/macau/viewpoint.png'),
        location: require('../../source/macau/location.png'),
        call: require('../../source/macau/call.png'),
        rate1: require('../../source/macau/rate1.png'),
        rate2: require('../../source/macau/rate2.png'),
        down: require('../../source/macau/down.png'),
        down2: require('../../source/macau/down2.png'),
        night: require('../../source/macau/night.png'),
        right: require('../../source/macau/right.png'),
        star: require('../../source/macau/star.png'),
        up: require('../../source/macau/up.png'),
        price1: require('../../source/macau/price1.png'),
        price2: require('../../source/macau/price2.png'),
        price1_red: require('../../source/macau/price1_red.png'),
        price2_red: require('../../source/macau/price2_red.png'),
        callPhone: require('../../source/macau/callPhone.png'),
        notRoom: require('../../source/macau/notRoom.png'),
        bg_music: require('../../source/macau/bg_music.png'),
        bg_music_close: require('../../source/macau/bg_music_close.png'),
        top: require('../../source/macau/top.png'),
        bth: require('../../source/macau/bth.png')


    },
    integral: {
        integral: require('../../source/integral/integral.png'),
        hotel: require('../../source/integral/hotel.png'),
        frends: require('../../source/integral/frends.png'),
        jine: require('../../source/integral/jine.png'),
        login: require('../../source/integral/login.png'),
        monents: require('../../source/integral/monents.png'),
        renwu: require('../../source/integral/renwu.png'),
        share: require('../../source/integral/share.png'),
        tiezi: require('../../source/integral/tiezi.png'),
        coupon: require('../../source/integral/coupon.png'),
        couponTop: require('../../source/integral/couponTop.png'),
        couponBootom: require('../../source/integral/couponBootom.png'),
        exchange:require('../../source/integral/exchange.png')
    },
    coupon: {
        background: require('../../source/coupon/background2.png'),
        coupon: require('../../source/coupon/coupon.png'),
        return_hei: require('../../source/coupon/return_hei.png'),
        selected: require('../../source/coupon/selected.png'),
        unSelected: require('../../source/coupon/unSelected.png'),
        coupon_used: require('../../source/coupon/coupon_used.png'),
        croup_receive: require('../../source/coupon/croup_receive.png')

    },
    wallet: {
        get_cash: require('../../source/wallet/get_cash.png'),
        card: require('../../source/wallet/card.png'),
        record: require('../../source/wallet/record_money.png'),
        invite: require('../../source/wallet/invite.png'),
        bg: require('../../source/wallet/bg.png'),
        friends: require('../../source/wallet/friends.png'),
        moneys: require('../../source/wallet/moneys.png'),
        rlue: require('../../source/wallet/rlue.png'),
        rule2: require('../../source/wallet/rule2.png'),
        dddd: require('../../source/wallet/dddd.png')
    },
    navigation2: {
        weather: require('../../source/navigation/weather.png'),
        round_trip: require('../../source/navigation/round_trip.png'),
        fast_food: require('../../source/navigation/fast_food.png'),
        convenient: require('../../source/navigation/convenient.png'),
        hotline: require('../../source/navigation/hotline.png'),
        call_bg:require('../../source/navigation/call_bg.png'),
        car_bg:require('../../source/navigation/car_bg.png'),
        coupon_bg:require('../../source/navigation/coupon_bg.png'),
        ferry_bg:require('../../source/navigation/ferry_bg.png'),
        hotel_bg:require('../../source/navigation/hotel_bg.png'),
        info_ng:require('../../source/navigation/info_ng.png'),
        mall_bg:require('../../source/navigation/mall_bg.png'),
        raiders_bg:require('../../source/navigation/raiders_bg.png'),
        rate_bg:require('../../source/navigation/rate_bg.png'),
        rec_bg:require('../../source/navigation/rec_bg.png'),
        shop_bg:require('../../source/navigation/shop_bg.png'),
        visa:require('../../source/navigation/visa.png'),
        tehui:require('../../source/navigation/tehui.png'),
        show1:require('../../source/navigation/show1.png'),
        show2:require('../../source/navigation/show2.png')
    },
    fastBtn: {
        round1: require('../../source/fastBtn/round1.jpeg'),
        round2: require('../../source/fastBtn/round2.jpeg'),
        round3: require('../../source/fastBtn/round3.jpeg'),
        round4: require('../../source/fastBtn/round4.jpeg'),
        round5: require('../../source/fastBtn/round5.jpeg'),
        round6: require('../../source/fastBtn/round6.jpeg')
    },
    lottery:{
        opportunity:require('../../source/lottery/opportunity.png'),
        ward_add:require('../../source/lottery/ward_add.png'),
        rule_close:require('../../source/lottery/rule_close.png'),
        cus_service:require('../../source/lottery/cus_service.png'),
        activities:require('../../source/lottery/activities.png')
    }


};

export default images

